--NGUYỄN THANH SANG
--C3(10-12)
--1 THÊM DỮ LIỆU BẰNG LỆNH INSERT
--1.1. BẢNG NHÓM SP
USE QLBH
	DELETE FROM CTHD
	DELETE FROM HOADON
	DELETE FROM KHACHHANG
	DELETE FROM SANPHAM
	DELETE FROM NHACUNGCAP
	DELETE FROM NHOMSANPHAM
--1. NHẬP DỮ LIỆU CHO BẢNG NHÓM SẢN PHẨM
	INSERT NHOMSP VALUES(1,N'ĐIỆN TỬ')
SELECT * FROM NHOMSP -- XEM THÔNG TIN	
	--XÓA DÒNG
	DELETE FROM NHOMSP WHERE MANHOM = 1
	INSERT NHOMSP VALUES(2,N'GIA DỤNG'), (3,N'DỤNG CỤ GIA ĐÌNH')
--TĂNG KÍCH THƯỚC TÊN NHÓM
ALTER TABLE NHOMSP ALTER COLUMN TENNHOM NVARCHAR(30)
	INSERT NHOMSP VALUES(2,N'GIA DỤNG'),(3,N'DỤNG CỤ GIA ĐÌNH'),(4,N'CÁC MẶT HÀNG')
SELECT *FROM NHOMSP
--2 NHẬP BẢNG NHÀ CUNG CẤP
	INSERT NHACUNGCAP VALUES(1,N'CÔNG TY TNHH PHƯƠNG NAM',N'1 LÊ LỢI PHƯỜNG 4 QUẬN GÒ VẤP','0122536566','THANHSANG@GMAIL.COM')
	INSERT NHACUNGCAP VALUES(1,N'CÔNG TY TNHH LAN NGỌC',N'3 LÊ LỢI PHƯỜNG 4 QUẬN GÒ VẤP','012257855','THANHSANGGL@GMAIL.COM')
--3 NHẬP BẢNG SẢN PHẨM
--LIỆT KÊ CÁC CỘT RA 
	INSERT SANPHAM(MASP, TENSP,DVT,GIAGOC.SLTON,MANCC,MANHOM,MOTA)
		VALUES(1,N'MÁY TÍNH',N'CÁI',7000,100,1,1,N'MÁY TÍNH SONY RAM 2GB')
SELECT *FROM SANPHAM
--NHẬP DÒNG 6 CÓ THUỘC TÍNH CHỨA GÓA TRỊ NULL
--CÁCH 1 
INSERT SANPHAM VALUES(6,N'LÒ VI SÓNG',2,'',3,N'CÁI',1000000,20)
--CÁCH 2 LIỆT KÊ CÁI CỘT CẦN THÊM
INSERT SANPHAM(MASP,TENSP,DVT,GIAGOC,SLTON,MANCC,MANHOM)
	VALUES(6,N'LÒ VI SÓNG',N'CÁI',1000000,20,2,3)
INSERT SANPHAM VALUES(4,N'CHUỘT',1,N'CHUỘT KHÔNG DÂY',1,N'CÁI',800,150)
INSERT SANPHAM VALUES(7,N'CPU',1,N'CPU',1,N'CÁI',3000,200)
INSERT SANPHAM VALUES(7,N'USB',1,N'8GB',1,N'CÁI',500,100)
ALTER TABLE KHACHHANG 
	ADD DIEMTL INT
INSERT KHACHHANG (MAKH,TENKH,LOAIKH,DIACHI)
	VALUES('KH1',N'NGUYỄN THU HẰNG','VIP',N'12 NGUYỄN DU')
INSERT KHACHHANG(MAKH,TENKH,DIACHI,PHONE,LOAIKH,DCMAIL)
	VALUES('KH2',N'LÊ MINH',N'34 ĐIỆN BIÊN PHỦ','090909909','TV','LEMINH@YAHOO.COM'),
	('KH3',N'NGUYỄN MINH TRUNG',N'3LÊ LỢI','097809909','VIP','TRUNG@YAHOO.COM')
SELECT *FROM KHACHHANG
-- NHẬP BẢNG HÓA ĐƠN
-- CHUYỂN SANG DẠNG NGÀY/THÁNG/NĂM
SET DATEFORMAT DMY
INSERT HOADON
	VALUES(1,'30/10/2021','15/11/2021',N'CỬA HÀNG 1BC 3 LÝ CHÍNH THẮNG Q3','KH1')
SELECT * FROM HOADON
DELETE FROM HOADON WHERE MAHD = 1
---------
INSERT HOADON(MAHD,NGAYLAP,NGAYGIAO,MAKH)
	VALUES(2,GETDATE(),'30/4/2022', 'KH2')
	,(3,GETDATE(),'15/11/2021','KH1')

INSERT CTHD(MAHD,MASP,DONGIA,SOLUONG)
	VALUES(2,1,8000,5),(2,2,1200,4),(2,3,1000,15)
--CẬP NHẬT DỮ LIỆU
SELECT * FROM SANPHAM
--A TĂNG ĐƠN GIÁ BÁN LÊN 5% CHO CÁC SẢN PHẨM
UPDATE SANPHAM 
	SET DONGIA = DONGIA + (DONGIA*5*1.0)/100
--B TĂNG SỐ LƯỢNG TỒN LÊN 100 CHO CÁC SẢN PHẨM CÓ MÃ NHÓM LÀ 3 VÀ MÃ
-- NHÀ CUNG CẤP CÓ MÃ LÀ 2
	UPDATE SANPHAM	
		SET SLTON = SLTON + 100
		WHERE MANHOM = 3 AND MANCC=2
--C TĂNG ĐIỂM TÍCH LŨY LÊN 50 CHO NHỮNG KHÁCH HÀNG KHÔNG PHẢI VÃNG LAI
SELECT *FROM KHACHHANG
ALTER TABLE KHACHHANG
	ADD DIEMTL INT
UPDATE KHACHHANG
SET DIEMTL = TIEMTL+50
WHERE LOAIKH<>'VL'
--
UPDATE KHACHHANG 
SET DIEMTL = 0
-- CẬP NHẬT CỘT MÔ TẢ CHO SẢN PHẨM CÓ TÊN LÒ VI SÓNG
SELECT * FROM SANPHAM
UPDATE SANPHAM
SET MOTA=N'LÒ VI SÓNG PHILIP'
WHERE TENSP=N'LÒ VI SÓNG'
--E TĂNG ĐƠN GIÁ GỐC LÊN 2% CHO NHỮNG SÃN PHẨM CHỨA CHỮ U
SELECT * FROM SANPHAM
UPDATE SANPHAM	
	SET GIAGOC = GIAGOC +(GIAGOC*2*1.0)/100
	WHERE TENSP LIKE '%U%'
-- XÓA DỮ LIỆU
-- DÙNG LỆNH DELETE THUWCK HIỆN CÁC YÊU CẦU SAU
-- XÓA CÁC SẢN PHẨM CÓ SLTON <2
DELETE FROM SANPHAM WHERE SLT <2
-- XÓA CÁC HÓA ĐƠN CỦA KHÁC HÀNG VÃNG LAI
SELECT * FROM HOADON
DELETE FROM HOADON WHERE MAKH IN(SELECT MAKH FROM KHACHHANG WHERE LOAIKH='VIP')
-- XÓA KHÁCH HÀNG THUỘC LOẠI VIP MÀ CÓ ĐIỂM TÍCH LŨY BẰNG 0
SELECT * FROM KHACHHANG
DELETE FORM KHACHHANG WHERE LOAIkh = 'VIP' AND DIEMTL = 0
SELECT * FROM KHACHHANG
SELECT * FROM HOADON
