--NGUYỄN THANH SANG
--LỚP DHKTPM16ATT
--C3(10-12)
--1. TẠO CSDL MOVIES
CREATE DATABASE MOVIES
ON PRIMARY
	(NAME = 'MOVIES_DATA',
	FILENAME = 'D:\HECSDL\MOVIES_DATA.MDF',
	SIZE = 25,
	MAXSIZE = 40,
	FILEGROWTH = 1)
LOG ON
	(NAME = 'MOVIES_LOG',
	FILENAME = 'D:\HECSDL\MOVIES_LOG.NDF',
	SIZE = 6,
	MAXSIZE = 8,
	FILEGROWTH =1)
--1.2.MỞ CSDL ĐỂ SD
	USE MOVIES
--2 KIỂM TRA KQ SAU MỖI LẦN THỰC HIỆN
SP_HELPDB
--Thêm một Datafile thứ 2 có Name: Movies_data2; pathname: C:\Movies\Movies_data2.ndf; Size: 10 MB; thông số khác không cần chỉ định.
ALTER DATABASE MOVIES
	ADD File (Name =MOVIES_DATA2,
	Filename ='D:\HECSDL\MOVIES_DATA2.NDF',
	SIZE =10 MB)
SP_HELPDB MOVIES
--Tăng kích cỡ của data file thứ 2 từ 10 MB lên 15 MB. Kiểm tra lại
ALTER DATABASE MOVIES
		MODIFY FILE(NAME='MOVIES_DATA2',SIZE=15)
SP_HELPDB MOVIES
--3 BỔ SUNG CÂU LỆNH TẠO FILEGROUP
ALTER DATABASE MOVIES
		ADD FILEGROUP DATA
-- HIỆU CHỈNH MAXSIZE CỦA TẬP TIN TRANSACTION LOG THÀNH 10MB
ALTER DATABASE MOVIES
	MODIFY FILE(NAME = 'MOVIES_LOG',MAXSIZE = 10)
-- HIỆU CHỈNH FILE CỦA TẬP TIN DATA THỨ 2 THÀNH 10MB
ALTER DATABASE MOVIES
	MODIFY FILE(NAME = 'MOVIES_DATA2',SIZE = 10) -- KHÔNG CHỈNH SỬA ĐƯỢC SIZE
--CHO DATA FILE THỨ 2 NẰM TRONG FILEGROUP DATA
ALTER DATABASE MOVIES
	ADD FILE(NAME = 'MOVIES_DATA2',
			 FILENAME = 'D:\HECSDL\MOVIES_DATA2.NDF',
			 SIZE = 10,
			 FILEGROWTH =1)
	TO FILEGROUP DATA
SP_HELPDB
--4 TẠO CÁC BẢNG
USE MOVIES
CREATE TABLE MOVIE(MAPHIM INT, TENPHIM NVARCHAR(40), SLT INT, MATHELOAI INT)
CREATE TABLE CUSTOMER (MAKH INT, HOTEN NVARCHAR(40), DIACHI NVARCHAR(60))
CREATE TABLE CATEGORY (MATHELOAI INT, TENTHELOAI NVARCHAR(20))
CREATE TABLE RENTAL(MATHUE INT , MAKH INT, NGAYTHUE DATE, NGAYTRA DATE)
CREATE TABLE RENTAL_DETAIL(MATHUE INT, MAPHIM INT, DONGIA MONEY, SOLUONG INT, THANHTIEN AS SOLUONG*DONGIA)
-- THÊM CÁC RÀNG BUỘC 
--5.1 THÊM RÀNG BUỘC KHÓA CHÍNH
-- THÊM RÀNG BUỘC KHÓA CHÍNH CHO BẢNG MOVIE
ALTER TABLE MOVIE
	ALTER COLUMN MAPHIM INT NOT NULL
ALTER TABLE MOVIE 
	ADD CONSTRAINT PK_MAPHIM PRIMARY KEY(MAPHIM)
--THÊM RÀNG BUỘC KHÓA CHÍNH CHO BẢNG CUSTOMER
ALTER TABLE CUSTOMER
	ALTER COLUMN MAKH INT NOT NULL
ALTER TABLE CUSTOMER
	ALTER COLUMN HOTEN NVARCHAR NOT NULL
ALTER TABLE CUSTOMER 
	ADD CONSTRAINT PK_MAKH PRIMARY KEY(MAKH)
--THÊM RÀNG BUỘC KHÓA CHÍNH CHO BẢNG CATEGORY
ALTER TABLE CATEGORY
	ALTER COLUMN MATHELOAI INT NOT NULL
ALTER TABLE CATEGORY
	ADD CONSTRAINT PK_MATHELOAI PRIMARY KEY(MATHELOAI)
--THÊM RÀNG BUỘC KHÓA CHÍNH CHO BẢNG RENTAL
ALTER TABLE RENTAL
	ALTER COLUMN MATHUE INT NOT NULL
ALTER TABLE RENTAL
	ADD CONSTRAINT PK_MATHUE PRIMARY KEY(MATHUE)
--THÊM RÀNG BUỘC KHÓA CHÍNH CHO BẢNG RENTAL_DETAIL
ALTER TABLE RENTAL_DETAIL
	ALTER COLUMN MATHUE INT NOT NULL
ALTER TABLE RENTAL_DETAIL
	ALTER COLUMN MAPHIM INT NOT NULL
ALTER TABLE RENTAL_DETAIL
	ADD CONSTRAINT PK_MATHUE_MAPHIM PRIMARY KEY(MATHUE,MAPHIM)
--5.2 THÊM RÀNG BUỘC KHÓA NGOẠI
ALTER TABLE MOVIE
		ADD CONSTRAINT FK_MATHELOAI FOREIGN KEY(MATHELOAI) REFERENCES CATEGORY(MATHELOAI)
		ON DELETE CASCADE
		ON UPDATE CASCADE
ALTER TABLE RENTAL
		ADD CONSTRAINT FK_MAKH FOREIGN KEY(MAKH) REFERENCES CUSTOMER(MAKH)
		ON DELETE CASCADE
		ON UPDATE CASCADE
ALTER TABLE RENTAL_DETAIL
		ADD CONSTRAINT FK_MATHUE FOREIGN KEY(MATHUE) REFERENCES RENTAL(MATHUE)
		ON DELETE CASCADE
		ON UPDATE CASCADE
ALTER TABLE RENTAL_DETAIL
		ADD CONSTRAINT FK_MAPHIM FOREIGN KEY(MAPHIM) REFERENCES MOVIE(MAPHIM)
		ON DELETE CASCADE
		ON UPDATE CASCADE
-- THÊM RÀNG BUỘC QUI ĐỊNH NHẬP DỮ LIỆU 
ALTER TABLE RENTAL
		ADD CONSTRAINT DF_NGAYTHUE DEFAULT GETDATE() FOR NGAYTHUE
ALTER TABLE RENTAL
		ADD CONSTRAINT CK_NGAYTRA CHECK(NGAYTRA>=NGAYTHUE)
ALTER TABLE CATEGORY
		ADD CONSTRAINT CK_TENTHELOAI CHECK (TENTHELOAI IN(N'HÀNH ĐỘNG',N'KINH DỊ',N'TÌNH CẢM',N'HÀI HƯỚC',N'HOẠT HÌNH'))
SP_HELPDB MOVIES






