--Nguyễn Thanh Sang
--Lớp DHKTPM16BTT
--C3 Tiết 10-12
--1. TẠO CSDL
--C1. DÙNG CÔNG CỤ DESIGN
--C2. TẠO BẰNG LỆNH
CREATE DATABASE QLBH
ON PRIMARY
	(NAME ='QLBH_DATA',
	FILENAME='D:\HECSDL\QLBH_DATA.MDF',
	SIZE=6,
	MAXSIZE=10,
	FILEGROWTH =1)
LOG ON
	(NAME ='QLBH_LOG',
	FILENAME='D:\HECSDL\QLBH_LOG.LDF',
	SIZE=2,
	MAXSIZE=8,
	FILEGROWTH =1)
CREATE DATABASE QLSACH
ON PRIMARY
	(NAME ='QLSACH_DATA',
	FILENAME='D:\HECSDL\QLSACH_DATA.MDF',
	SIZE=20,
	MAXSIZE=40,
	FILEGROWTH =1)
LOG ON
	(NAME ='QLSACH_LOG',
	FILENAME='D:\HECSDL\QLSACH_LOG.LDF',
	SIZE=6,
	MAXSIZE=8,
	FILEGROWTH =1)
--2. MỞ CSDL ĐỂ SỬ DỤNG
USE QLSV
--3.1 XEM TRỢ GIÚP THÔNG TIN VỀ CSDL TRONG SEVER HIỆN HÀNH
SP_HELPDB
--3.2 XEM TRỢ GIÚP THÔNG TIN CỦA 1 CSDL
SP_HELPDB QLSACH
--3.3 XEM KHÔNG GIAN SỬ DỤNG CỦA CSDL HIỆN HÀNH
SP_SPACEUSED
--4. TẠO CSDL CÓ FILE THỨ CẤP
CREATE DATABASE VATTU
ON PRIMARY
	(NAME='VATTU_DATA',
	FILENAME='D:\HECSDL\VATTU_DATA.MDF',
	SIZE = 5,
	MAXSIZE =10, 
	FILEGROWTH=1),
	(NAME='VATTU_DATA1',
	FILENAME = 'D:\HECSDL\VATTU_DATA1.NDF',
	SIZE = 5,
	MAXSIZE =10,
	FILEGROWTH=1)
LOG ON
	(NAME='VATTU_LOG',
	FILENAME = 'D:\HECSDL\VATTU_LOG.LDF',
	SIZE = 2,
	MAXSIZE =6,
	FILEGROWTH=1)
SP_HELPDB VATTU
--5. SỬA CHỮA CẤU TRÚC CSDL
--5.1 THÊM VÀO FILEGROUP
	ALTER DATABASE VATTU
		ADD FILEGROUP SP
	USE VATTU
--5.1.2 XEM TRỢ GIÚP FILEGROUP
	SP_HELPFILEGROUP
--5.2 THÊM VÀO MỘT FILE THỨ CẤP ĐỂ VÀO FILEGROUP SP
	ALTER DATABASE VATTU
		ADD FILE(NAME ='VATTU_DATA2',
				 FILENAME = 'D:\HECSDL\VATTU_DATA2.NDF',
				 SIZE = 2,
				 MAXSIZE=6,
				 FILEGROWTH=1)
		TO FILEGROUP SP
	-- XEM TRỢ GIÚP 
	SP_HELPDB VATTU
--5.3 THAY ĐỔI KÍCH THƯỚC TẬP TIN
	ALTER DATABASE VATTU
		MODIFY FILE(NAME='VATTU_DATA2',SIZE=10)
	ALTER DATABASE VATTU
		MODIFY FILE(NAME='VATTU_DATA2',SIZE=12)
--5.4 XÓA FILEGROUP
	ALTER DATABASE VATTU
		REMOVE FILEGROUP SP --KHÔNG XÓA ĐƯỢC VÌ KHÔNG TRỐNG
	ALTER DATABASE VATTU
		REMOVE FILE VATTU_DATA2
--6 ĐẶT THUỘC TÍNH CHỈ ĐỌC CHO VATTU
	ALTER DATABASE VATTU
		SET READ_ONLY
	ALTER DATABASE VATTU
		SET READ_WRITE --ĐỌC VÀ GHI
--7. ĐỔI TÊN CSDL
	SP_RENAMEDB 'QLSV','SINHVIEN'
--8. XÓA CSDL
	DROP DATABASE VATTU
	USE MASTER
	DROP DATABASE QLBH
	DROP DATABASE QLSACH
	DROP DATABASE SINHVIEN


	