--Nguyễn Thanh Sang
--Lớp DHKTPM16BTT
--C3 Tiết 10-12
CREATE DATABASE QLSACH
ON PRIMARY
	(NAME ='QLSACH_DATA',
	FILENAME='D:\HECSDL\QLSACH_DATA.MDF',
	SIZE=20,
	MAXSIZE=40,
	FILEGROWTH =1)
LOG ON
	(NAME ='QLSACH_LOG',
	FILENAME='D:\HECSDL\QLSACH_LOG.LDF',
	SIZE=6,
	MAXSIZE=8,
	FILEGROWTH =1)

ALTER DATABASE QLSACH
		ADD FILEGROUP DULIEUSACH
ALTER DATABASE QLSACH
		ADD FILE(NAME ='QLSACH_DATA2',
				 FILENAME = 'D:\HECSDL\QLSACH_DATA2.NDF',
				 SIZE = 2,
				 MAXSIZE=6,
				 FILEGROWTH=1)
		TO FILEGROUP DULIEUSACH
ALTER DATABASE QLSACH
		SET READ_ONLY
	ALTER DATABASE QLSACH
		SET READ_WRITE
CREATE DATABASE QLBH
ON PRIMARY
	(NAME ='QLBH_DATA1',
	FILENAME='D:\HECSDL\QLBH_DATA1.MDF',
	SIZE=10,
	MAXSIZE=40,
	FILEGROWTH =1)
LOG ON
	(NAME ='QLBH_LOG',
	FILENAME='D:\HECSDL\QLBH_LOG.LDF',
	SIZE=6,
	MAXSIZE=8,
	FILEGROWTH =1)
SP_HELPDB
SP_SPACEUSED
SP_HELPFILE
ALTER DATABASE QLBH
		ADD FILEGROUP DULIEUQLBH
ALTER DATABASE QLBH
		ADD FILE(NAME ='QLBH_DATA2',
				 FILENAME = 'D:\HECSDL\QLBH_DATA2.NDF',
				 SIZE = 2,
				 MAXSIZE=6,
				 FILEGROWTH=1)
		TO FILEGROUP DULIEUQLBH
sp_helpfilegroup
ALTER DATABASE QLBH
		SET READ_ONLY
SP_HELPDB QLBH
ALTER DATABASE QLBH
		SET READ_WRITE
ALTER DATABASE QLBH
		MODIFY FILE(NAME='QLBH_DATA1',SIZE=50)
	ALTER DATABASE QLBH
		MODIFY FILE(NAME='QLBH_LOG',SIZE=10)
CREATE DATABASE QLSV
ON PRIMARY
	(NAME ='QLSV_DATA',
	FILENAME='D:\HECSDL\QLSV_DATA.MDF',
	SIZE=20,
	MAXSIZE=40,
	FILEGROWTH =1)
LOG ON
	(NAME ='QLSV_LOG',
	FILENAME='D:\HECSDL\QLSV_LOG.LDF',
	SIZE=6,
	MAXSIZE=8,
	FILEGROWTH =1)
SP_RENAMEDB 'QLSV','QLHS'
DROP DATABASE QLHS
